micronaut:
  application:
    name: geoPosApp
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2    
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
#jpa:
#  default:
#    properties:
#      hibernate:
#        id:
#          new_generator_mappings: false
#        dialect: org.hibernate.dialect.H2Dialect
#        hbm2ddl:
#          auto: update
#        show_sql: true